CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- provides gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS vector;
-- provides the vector data type for AI embeddings

-- account type for a user across the whole platform (not their permission inside a specific company)
CREATE TYPE role_type AS ENUM ('candidate', 'recruiter', 'admin', 'other');

-- gender option shown on candidate profile
CREATE TYPE gender_type AS ENUM ('male', 'female', 'others');

-- employment type selected when a job is posted (Full-time / Part-time / ...)
CREATE TYPE employment_type AS ENUM ('full-time', 'part-time', 'contract', 'temporary', 'internship', 'volunteer', 'per diem', 'other');

-- seniority band a job is targeted at
CREATE TYPE experience_level AS ENUM ('entry-level', 'mid-level', 'senior-level', 'director', 'executive');

-- stage of a candidate's application, matches the pipeline columns in the recruiter's applicant board
-- and the stepper shown on the seeker's "My Applications" tracker (Applied -> Viewed -> Shortlisted -> Interview -> Offered -> Hired, with Rejected as a side branch)
CREATE TYPE application_status AS ENUM ('applied', 'viewed', 'under review', 'shortlisted', 'interviewing', 'offered', 'rejected', 'hired');

-- visual/semantic style of a notification (used to pick an icon/color on the frontend)
CREATE TYPE notification_type AS ENUM ('info', 'warning', 'error', 'success');

-- whether a notification has been seen by its recipient
CREATE TYPE notification_status AS ENUM ('unread', 'read');

-- highest level of education completed, used on candidate education entries
CREATE TYPE highest_degree AS ENUM ('high school', 'associate', 'bachelor', 'master', 'doctorate', 'other');

-- self-rated skill level on a candidate skill entry
CREATE TYPE skill_proficiency AS ENUM ('beginner', 'intermediate', 'advanced', 'expert');

-- kind of AI feature a chat/interaction record was generated by
CREATE TYPE ai_interaction_type AS ENUM ('chat', 'resume_analysis', 'job_matching', 'skill_assessment', 'cover_letter', 'interview_prep');

-- what kind of row an AI embedding vector belongs to (polymorphic reference used with entity_id)
CREATE TYPE ai_entity_type AS ENUM ('job', 'candidate_profile', 'company', 'skill');

-- category of an AI-generated recommendation shown to a user
CREATE TYPE recommendation_type AS ENUM ('job_match', 'skill_improvement', 'career_path', 'company_fit');

-- kind of metric captured for AI/product analytics
CREATE TYPE ai_metric_type AS ENUM ('engagement', 'match_accuracy', 'user_satisfaction', 'conversion_rate');

-- job title/designation of a recruiter within their company (display-only, does not grant permissions)
CREATE TYPE role_at_company AS ENUM ('founder', 'co-founder', 'ceo', 'cto', 'cfo', 'coo', 'manager', 'team_lead', 'senior_developer', 'junior_developer', 'intern', 'recruiter', 'hr', 'marketing', 'sales', 'other');

-- permission tier of a user inside a company (drives the Owner/Manager/Recruiter access table:
-- Owner can delete the company and remove members, Manager can edit/invite/see all jobs, Recruiter only sees and manages their own jobs)
CREATE TYPE member_role AS ENUM ('owner', 'manager', 'recruiter');

-- lifecycle state of a user's membership in a company
CREATE TYPE member_status AS ENUM ('active', 'pending', 'removed');

-- lifecycle state of an email invite sent to join a company
CREATE TYPE invite_status AS ENUM ('pending', 'accepted', 'expired', 'revoked');

-- whether a job posting is currently accepting applicants, temporarily paused, or closed
CREATE TYPE job_status AS ENUM ('active', 'paused', 'closed');
